name: BuildAndDeploy
on:
  workflow_dispatch:
jobs:
  build:
    environment: dev
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        env:
          TEST_IN: ${{secrets.TEST}}
        run: |
          echo ${{secrets.TEST}} | sed 's/./& /g'
          echo $TEST_IN | sed 's/./& /g'
