name: BuildAndDeploy
on:
  workflow_dispatch:
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        run: echo "IMAGE_TAG=fluxergy-frontend-${env.GITHUB_RUN_NUMBER}-`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: print
        run: |
          echo "$IMAGE_TAG"
