name: BuildAndDeploy
on:
  workflow_dispatch:
env:
  ENV_NAME: fluxergy-frontend
jobs:
  build:
    environment: dev
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        id: vars
        run: | 
          echo "${{ secrets.TEST }}"
          
