name: BuildAndDeploy
on:
  workflow_dispatch:
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        id: vars
        run: echo "docker_tag=$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}" >> $GITHUB_OUTPUT
      - name: print
        run: |
          echo "${{ steps.vars.outputs.docker_tag }}"
